import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Github, Linkedin, Mail, Menu, X, Sun, Moon, ExternalLink, Download, Award, Code2, Cpu, Database, Phone, MapPin, Send, ArrowUp, Brain, CheckCircle2, Star, Zap, BarChart3, Layers, BookOpen, TrendingUp } from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, PieChart, Pie } from "recharts";
import { NAV_LINKS, SKILL_CATEGORIES, PROJECTS, ML_JOURNEY, DSA_ALGO_TAGS, DSA_DS_TAGS, DSA_BAR_DATA, CERTS, EXPERIENCE, ACHIEVEMENTS, TOP_LANGS, BLOGS, TESTIMONIALS, CONTRIBS, CONTRIB_COLORS, CONTRIB_COLORS_LIGHT, CODE_LINES } from "../../../data/portfolio-data.js";
import { Reveal, SectionHeader, GradientText, Card } from "../common/PortfolioCommon.jsx";

export function Blogs() {
  return (
    _jsx("section", { id: "blogs", className: "py-24 bg-slate-50 dark:bg-[#0a0f1e]", children: _jsxs("div", { className: "max-w-6xl mx-auto px-6", children: [_jsx(Reveal, { children: _jsx(SectionHeader, { badge: "Writing", title: "Blogs & Articles", subtitle: "Sharing what I learn about ML, DSA, and data science with the community." }) }), _jsx("div", { className: "grid sm:grid-cols-2 lg:grid-cols-4 gap-5", children: BLOGS.map((b, i) => (_jsx(Reveal, { delay: i * 70, children: _jsxs("div", { className: "group bg-white dark:bg-slate-800 border border-slate-100 dark:border-slate-700 rounded-2xl overflow-hidden hover:shadow-lg hover:-translate-y-1 transition-all", children: [_jsxs("div", { className: "relative h-36 bg-slate-100 dark:bg-slate-700 overflow-hidden", children: [_jsx("img", { src: `https://images.unsplash.com/${b.image}?w=400&h=180&fit=crop&auto=format`, alt: b.title, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" }), _jsx("div", { className: "absolute top-2 left-2 text-xs px-2 py-0.5 bg-blue-600 text-white rounded-lg", children: b.cat })] }), _jsxs("div", { className: "p-4", children: [_jsx("h4", { className: "font-bold text-slate-900 dark:text-white text-xs leading-snug mb-2 line-clamp-2", style: { fontFamily: "'Poppins', sans-serif" }, children: b.title }), _jsxs("div", { className: "flex items-center justify-between text-xs text-slate-400 mb-3", children: [_jsx("span", { children: b.date }), _jsxs("span", { children: [b.readTime, " read"] })] }), _jsxs("a", { href: "#", className: "text-xs text-blue-600 dark:text-blue-400 font-medium hover:underline flex items-center gap-1", children: ["Read More ", _jsx(ExternalLink, { className: "w-3 h-3" })] })] })] }) }, b.title))) })] }) })
  );
}
